apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "renovate-trigger.fullname" . }}
  namespace: {{ .Values.config.cronjob.namespace | default .Release.Namespace }}
  labels:
    {{- include "renovate-trigger.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "list"]
